### PR TITLE
add clearCookie

### PR DESCRIPTION
**Pull request by jurihahn**
function to delete all cookies

for #10

### CODE REVIEW

**Review by NiklasMerz — APPROVED** [review]
Code looks good to me and I did not find any issues with a short test. Thank you for this.

Good job 🥇

**Comment by NiklasMerz** [comment]
Documentation for this function would be awesome.

I will merge this for the next version but I might take some time for a release as I am waiting for the next cordova-android release.

**Comment by jurihahn** [comment]
small info about clearCookie function added

**Comment by NiklasMerz** [comment]
Thanks. Awesome.

**Pull request merged**
